# Generated by Django 3.2.25 on 2025-09-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250908_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='+254', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('CUSTOMER', 'Customer')], max_length=50, null=True),
        ),
    ]
