# Generated by Django 3.2.25 on 2025-09-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250908_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
