# Generated by Django 4.2.16 on 2025-09-23 13:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_insurancequotation_serviceprocessinglog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('supported_categories', models.JSONField(blank=True, default=list)),
                ('supported_payment_methods', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotorCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('pricing_type', models.CharField(default='dynamic', max_length=50)),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleAdjustmentFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('factor_code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('factor_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PSVPLLPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(default='STANDARD', max_length=100)),
                ('pll_rate_per_person', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('underwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psv_pll', to='app.insuranceprovider')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotorSubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subcategory_code', models.CharField(max_length=80)),
                ('subcategory_name', models.CharField(max_length=150)),
                ('product_type', models.CharField(choices=[('fixed', 'Fixed'), ('third_party', 'Third Party'), ('comprehensive', 'Comprehensive'), ('tonnage', 'Commercial Tonnage'), ('psv', 'PSV')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_fields', models.JSONField(blank=True, default=list)),
                ('field_validations', models.JSONField(blank=True, default=dict)),
                ('pricing_requirements', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.motorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MotorPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insurance_training_levy_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0025'), max_digits=5)),
                ('pcf_levy_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0025'), max_digits=5)),
                ('stamp_duty', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sum_insured_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sum_insured_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_rate_min', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('base_rate_max', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('minimum_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('excess_protector_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('excess_protector_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pvt_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('pvt_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loss_of_use_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loss_of_use_coverage', models.IntegerField(blank=True, null=True)),
                ('windscreen_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('windscreen_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('radio_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('radio_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('pricing_factors', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='app.motorsubcategory')),
                ('underwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_pricing', to='app.insuranceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialTonnagePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tonnage_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tonnage_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tonnage_description', models.CharField(max_length=100)),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fleet_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_fleet_pricing', models.BooleanField(default=False)),
                ('is_prime_mover', models.BooleanField(default=False)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tonnage_pricing', to='app.motorsubcategory')),
                ('underwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_tonnage', to='app.insuranceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFieldPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field_code', models.CharField(max_length=50)),
                ('pricing_data', models.JSONField(default=dict)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_pricing', to='app.motorsubcategory')),
            ],
        ),
        migrations.AddIndex(
            model_name='motorsubcategory',
            index=models.Index(fields=['subcategory_code'], name='app_motorsu_subcate_2244fe_idx'),
        ),
        migrations.AddIndex(
            model_name='motorsubcategory',
            index=models.Index(fields=['product_type'], name='app_motorsu_product_962074_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='motorsubcategory',
            unique_together={('category', 'subcategory_code')},
        ),
        migrations.AddIndex(
            model_name='motorpricing',
            index=models.Index(fields=['effective_from'], name='app_motorpr_effecti_422a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='motorpricing',
            index=models.Index(fields=['subcategory'], name='app_motorpr_subcate_de9e23_idx'),
        ),
        migrations.AddIndex(
            model_name='motorpricing',
            index=models.Index(fields=['underwriter'], name='app_motorpr_underwr_d2a02b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='motorpricing',
            unique_together={('underwriter', 'subcategory', 'sum_insured_min', 'effective_from')},
        ),
        migrations.AddIndex(
            model_name='commercialtonnagepricing',
            index=models.Index(fields=['subcategory'], name='app_commerc_subcate_e8bd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialtonnagepricing',
            index=models.Index(fields=['tonnage_min', 'tonnage_max'], name='app_commerc_tonnage_f80068_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='additionalfieldpricing',
            unique_together={('subcategory', 'field_code', 'effective_from')},
        ),
    ]
