# Generated by Django 4.2.16 on 2025-09-23 19:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_insuranceprovider_motorcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorsubcategory',
            name='extendible_variant',
            field=models.ForeignKey(blank=True, help_text='Link to the extendible variant of this product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.motorsubcategory'),
        ),
        migrations.AddField(
            model_name='motorsubcategory',
            name='is_extendible',
            field=models.BooleanField(default=False, help_text='Can this product be sold as extendible?'),
        ),
        migrations.CreateModel(
            name='PolicyExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('product_name', models.CharField(max_length=200)),
                ('initial_premium_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_start_date', models.DateField()),
                ('initial_expiry_date', models.DateField()),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extension_status', models.CharField(choices=[('pending', 'Pending Extension'), ('reminded', 'Reminder Sent'), ('extended', 'Successfully Extended'), ('expired', 'Expired Without Extension'), ('grace_period', 'In Grace Period')], default='pending', max_length=20)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('extension_payment_date', models.DateTimeField(blank=True, null=True)),
                ('extension_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_certificate_issued', models.BooleanField(default=False)),
                ('final_expiry_date', models.DateField(blank=True, null=True)),
                ('auto_reminder_enabled', models.BooleanField(default=True)),
                ('underwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.insuranceprovider')),
            ],
            options={
                'verbose_name': 'Policy Extension',
                'verbose_name_plural': 'Policy Extensions',
                'ordering': ['initial_expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('app_notification', 'App Notification'), ('phone_call', 'Phone Call')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('responded', 'Customer Responded')], default='scheduled', max_length=20)),
                ('message_template', models.TextField()),
                ('personalized_message', models.TextField(blank=True)),
                ('delivery_channel', models.CharField(blank=True, max_length=100)),
                ('delivery_status', models.CharField(blank=True, max_length=100)),
                ('customer_response', models.TextField(blank=True)),
                ('customer_response_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('policy_extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='app.policyextension')),
            ],
            options={
                'verbose_name': 'Extension Reminder',
                'verbose_name_plural': 'Extension Reminders',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ExtendiblePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('initial_period_days', models.PositiveIntegerField(default=30)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_annual_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extension_deadline_days', models.PositiveIntegerField(default=30)),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('cover_note_template', models.TextField(blank=True)),
                ('full_certificate_template', models.TextField(blank=True)),
                ('extension_reminder_template', models.TextField(blank=True)),
                ('auto_reminder_schedule', models.JSONField(default=list)),
                ('penalty_for_late_extension', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('allow_partial_extension', models.BooleanField(default=False)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.motorsubcategory')),
                ('underwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.insuranceprovider')),
            ],
            options={
                'verbose_name': 'Extendible Pricing',
                'verbose_name_plural': 'Extendible Pricing',
                'unique_together': {('subcategory', 'underwriter')},
            },
        ),
    ]
