# Generated by Django 4.2.16 on 2025-09-23 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_motorsubcategory_extendible_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('campaign_type', models.CharField(choices=[('PROMOTIONAL', 'Promotional'), ('EDUCATIONAL', 'Educational'), ('SEASONAL', 'Seasonal'), ('PRODUCT_LAUNCH', 'Product Launch'), ('RETENTION', 'Customer Retention'), ('ACQUISITION', 'Customer Acquisition')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('target_roles', models.CharField(choices=[('ALL', 'All Users'), ('AGENT', 'Agents Only'), ('CUSTOMER', 'Customers Only'), ('NEW_USERS', 'New Users'), ('ACTIVE_AGENTS', 'Active Agents'), ('INACTIVE_AGENTS', 'Inactive Agents')], default='ALL', max_length=20)),
                ('target_regions', models.JSONField(blank=True, default=list)),
                ('target_age_min', models.IntegerField(blank=True, null=True)),
                ('target_age_max', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('call_to_action', models.CharField(max_length=100)),
                ('action_url', models.URLField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_impressions', models.IntegerField(blank=True, null=True)),
                ('target_clicks', models.IntegerField(blank=True, null=True)),
                ('target_conversions', models.IntegerField(blank=True, null=True)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='ONCE', max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('time_of_day', models.TimeField()),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('next_send', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.campaign')),
            ],
            options={
                'ordering': ['next_send'],
            },
        ),
        migrations.CreateModel(
            name='CampaignInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('interaction_type', models.CharField(choices=[('IMPRESSION', 'Impression'), ('CLICK', 'Click'), ('CONVERSION', 'Conversion'), ('DISMISS', 'Dismiss')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
