# Generated by Django 4.2.16 on 2025-09-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_pricing_model_and_rename_tonnage_fields'),
        ('app', '0010_motor_categories_enhancement'),
    ]

    operations = [
    ]
