# Generated by Django 4.2.16 on 2025-09-28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_motorpricing_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSVPLLPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pll_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_commercial_institutional', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pll_pricing', to='app.motorsubcategory')),
                ('underwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pll_pricing', to='app.insuranceprovider')),
            ],
            options={
                'ordering': ['-pll_amount'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='psvpllpricing',
            unique_together={('subcategory', 'underwriter', 'pll_amount', 'effective_from')},
        ),
    ]
