# Generated by Django 4.2.16 on 2025-09-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_populate_public_flags'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE app_motorcovertype DROP COLUMN IF EXISTS cover_type;",
            reverse_sql="ALTER TABLE app_motorcovertype ADD COLUMN cover_type VARCHAR(20) NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE app_motorinsurancedetails DROP COLUMN IF EXISTS cover_type;",
            reverse_sql="ALTER TABLE app_motorinsurancedetails ADD COLUMN cover_type VARCHAR(20) NULL;"
        ),
    ]
