# Generated by Django 4.2.16 on 2025-10-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_merge_20250930_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='processing_status',
            field=models.CharField(default='UPLOADED', max_length=20),
        ),
        migrations.CreateModel(
            name='MotorPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policy_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('quote_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_details', models.JSONField(help_text='Client information including name, email, phone, ID, KRA PIN, etc.')),
                ('vehicle_details', models.JSONField(help_text='Vehicle information including registration, make, model, year, value, etc.')),
                ('product_details', models.JSONField(help_text='Insurance product details including category, subcategory, coverage type')),
                ('underwriter_details', models.JSONField(blank=True, help_text='Selected underwriter information', null=True)),
                ('premium_breakdown', models.JSONField(help_text='Complete premium calculation with base premium, levies, and total')),
                ('payment_details', models.JSONField(help_text='Payment method, amount, reference, status')),
                ('addons', models.JSONField(blank=True, default=list, help_text='Selected additional coverage options')),
                ('documents', models.JSONField(blank=True, default=list, help_text='Uploaded document references')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING_PAYMENT', max_length=20)),
                ('cover_start_date', models.DateField(blank=True, null=True)),
                ('cover_end_date', models.DateField(blank=True, null=True)),
                ('policy_document_url', models.CharField(blank=True, max_length=500, null=True)),
                ('receipt_url', models.CharField(blank=True, max_length=500, null=True)),
                ('certificate_url', models.CharField(blank=True, max_length=500, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agent_code', models.CharField(blank=True, help_text='Sales agent code', max_length=50, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motor_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motor Policy',
                'verbose_name_plural': 'Motor Policies',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['policy_number'], name='app_motorpo_policy__d8cff4_idx'), models.Index(fields=['status', '-submitted_at'], name='app_motorpo_status_3f966f_idx'), models.Index(fields=['user', '-submitted_at'], name='app_motorpo_user_id_a28357_idx')],
            },
        ),
    ]
