# Generated by Django 4.2.16 on 2025-10-10 11:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_agentcommission_agentperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAgentBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year (e.g., 2025)')),
                ('period', models.CharField(db_index=True, help_text="e.g., '2025-10'", max_length=20)),
                ('total_policies', models.IntegerField(default=0, help_text='Number of ACTIVE policies in this period')),
                ('total_premium', models.DecimalField(decimal_places=2, default=0, help_text='Total premium from all ACTIVE policies', max_digits=12)),
                ('bonus_rate', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Bonus percentage (e.g., 0.30 for 0.3%)', max_digits=5)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated bonus amount', max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Monthly Agent Bonus',
                'verbose_name_plural': 'Monthly Agent Bonuses',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.RenameIndex(
            model_name='agentcommission',
            new_name='app_agentco_agent_i_9407d6_idx',
            old_name='app_agentco_agent_i_idx',
        ),
        migrations.RenameIndex(
            model_name='agentcommission',
            new_name='app_agentco_payment_b6e746_idx',
            old_name='app_agentco_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='agentperformance',
            new_name='app_agentpe_agent_i_f445c6_idx',
            old_name='app_agentpe_agent_i_idx',
        ),
        migrations.RenameIndex(
            model_name='agentperformance',
            new_name='app_agentpe_period_8f9e7d_idx',
            old_name='app_agentpe_period_idx',
        ),
        migrations.AddField(
            model_name='monthlyagentbonus',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bonuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='monthlyagentbonus',
            index=models.Index(fields=['agent', '-year', '-month'], name='app_monthly_agent_i_a37944_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyagentbonus',
            index=models.Index(fields=['payment_status', '-year', '-month'], name='app_monthly_payment_3c241f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyagentbonus',
            unique_together={('agent', 'period')},
        ),
    ]
