# Generated by Django 4.2.16 on 2025-10-10 19:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_monthlyagentbonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Percentage value, e.g. 15.00 for 15%', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Settings',
                'verbose_name_plural': 'Commission Settings',
            },
        ),
        migrations.RemoveIndex(
            model_name='agentcommission',
            name='app_agentco_agent_i_9407d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='agentcommission',
            name='app_agentco_payment_b6e746_idx',
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['agent', 'date_created'], name='app_agentco_agent_i_08093f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['payment_status', 'date_created'], name='app_agentco_payment_3c2007_idx'),
        ),
    ]
