# Generated by Django 4.2.16 on 2025-10-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_add_display_mode_to_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcovertype',
            name='category',
        ),
        migrations.DeleteModel(
            name='DomesticPackageManualQuoteProxy',
        ),
        migrations.DeleteModel(
            name='LastExpenseManualQuoteProxy',
        ),
        migrations.DeleteModel(
            name='MedicalManualQuoteProxy',
        ),
        migrations.DeleteModel(
            name='PersonalAccidentManualQuoteProxy',
        ),
        migrations.DeleteModel(
            name='TravelManualQuoteProxy',
        ),
        migrations.DeleteModel(
            name='WIBAManualQuoteProxy',
        ),
        migrations.DeleteModel(
            name='MotorCoverType',
        ),
    ]
