# Generated by Django 4.2.16 on 2025-10-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_campaign_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendiblePricing',
        ),
    ]
