# Generated by Django 4.2.16 on 2025-11-03 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_change_phone_to_10_digits_kenyan'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='motor_policy',
            field=models.ForeignKey(blank=True, help_text='Link to Motor 2 policy if applicable (for KYC documents)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='app.motorpolicy'),
        ),
        migrations.CreateModel(
            name='DMVICVehicleSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_number', models.CharField(db_index=True, help_text='Vehicle registration number (e.g., KCA123A)', max_length=20)),
                ('vehicle_data', models.JSONField(help_text='Complete vehicle details from DMVIC (make, model, year, chassis, etc.)')),
                ('search_timestamp', models.DateTimeField(auto_now_add=True, help_text='When the search was performed')),
                ('cache_expires_at', models.DateTimeField(help_text='When this cache entry expires (24 hours from search)')),
                ('has_existing_cover', models.BooleanField(default=False, help_text='True if DMVIC found existing active cover from another insurer')),
                ('existing_cover_details', models.JSONField(blank=True, help_text='Details of existing cover if found (insurer, policy number, dates)', null=True)),
                ('searched_by', models.ForeignKey(blank=True, help_text='User who initiated the search', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmvic_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DMVIC Vehicle Search',
                'verbose_name_plural': 'DMVIC Vehicle Searches',
                'ordering': ['-search_timestamp'],
                'indexes': [models.Index(fields=['registration_number', '-search_timestamp'], name='app_dmvicve_registr_bea383_idx'), models.Index(fields=['cache_expires_at'], name='app_dmvicve_cache_e_3204ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='DMVICCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate_number', models.CharField(blank=True, db_index=True, help_text='DMVIC-assigned certificate number (e.g., CHB432123)', max_length=50, null=True, unique=True)),
                ('certificate_type', models.CharField(choices=[('A', 'Type A - Third-Party'), ('B', 'Type B - Comprehensive'), ('C', 'Type C - Third-Party + PLL'), ('D', 'Type D - Comprehensive + PLL')], help_text='Certificate type determined by product coverage', max_length=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Issuance'), ('ISSUED', 'Successfully Issued'), ('FAILED', 'Issuance Failed'), ('CANCELLED', 'Certificate Cancelled')], db_index=True, default='PENDING', help_text='Current status of certificate issuance', max_length=20)),
                ('request_payload', models.JSONField(help_text='Exact payload sent to DMVIC API (for debugging)')),
                ('response_data', models.JSONField(blank=True, help_text='DMVIC API response (success or error details)', null=True)),
                ('dmvic_pdf_url', models.CharField(blank=True, help_text='URL to DMVIC-generated certificate PDF', max_length=500, null=True)),
                ('qr_code_url', models.CharField(blank=True, help_text='DMVIC QR code for certificate verification', max_length=500, null=True)),
                ('issued_at', models.DateTimeField(blank=True, help_text='When DMVIC successfully issued the certificate', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts (max 3)')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='Timestamp of last retry attempt', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details from DMVIC API (for debugging)')),
                ('motor_policy', models.ForeignKey(help_text='PataBima motor policy this certificate belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='dmvic_certificates', to='app.motorpolicy')),
            ],
            options={
                'verbose_name': 'DMVIC Certificate',
                'verbose_name_plural': 'DMVIC Certificates',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['certificate_number'], name='app_dmvicce_certifi_b377c3_idx'), models.Index(fields=['status', '-date_created'], name='app_dmvicce_status_a8647e_idx'), models.Index(fields=['motor_policy', '-date_created'], name='app_dmvicce_motor_p_4f7d70_idx')],
            },
        ),
    ]
