# Generated by Django 4.2.16 on 2025-11-04 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_motorpolicy_dmvic_api_request_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmvicvehiclesearch',
            options={'verbose_name': 'DMVIC Vehicle Search Cache', 'verbose_name_plural': 'DMVIC Vehicle Search Caches'},
        ),
        migrations.RemoveIndex(
            model_name='dmvicvehiclesearch',
            name='app_dmvicve_registr_bea383_idx',
        ),
        migrations.RemoveIndex(
            model_name='dmvicvehiclesearch',
            name='app_dmvicve_cache_e_3204ff_idx',
        ),
        migrations.RemoveField(
            model_name='dmvicvehiclesearch',
            name='cache_expires_at',
        ),
        migrations.RemoveField(
            model_name='dmvicvehiclesearch',
            name='existing_cover_details',
        ),
        migrations.RemoveField(
            model_name='dmvicvehiclesearch',
            name='search_timestamp',
        ),
        migrations.RemoveField(
            model_name='dmvicvehiclesearch',
            name='searched_by',
        ),
        migrations.RemoveField(
            model_name='dmvicvehiclesearch',
            name='vehicle_data',
        ),
        migrations.AddField(
            model_name='dmvicvehiclesearch',
            name='cached_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dmvicvehiclesearch',
            name='existing_cover_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmvicvehiclesearch',
            name='search_data',
            field=models.JSONField(default=dict, help_text='Raw JSON response from DMVIC search-vehicle API'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dmvicvehiclesearch',
            name='has_existing_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dmvicvehiclesearch',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
