# Generated by Django 4.2.16 on 2025-11-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_dmvicvehiclesearch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcategory',
            name='pricing_type',
            field=models.CharField(default='dynamic', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='action_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
