# Generated by Django 4.2.16 on 2025-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_increase_campaign_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='campaign_banners/'),
        ),
    ]
