# Generated by Django 4.2.16 on 2026-01-01 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_increase_banner_image_length'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE app_commercialtonnagepricing "
                "ADD COLUMN IF NOT EXISTS fleet_discount_percentage numeric(6,2) "
                "NOT NULL DEFAULT 0;"
            ),
            reverse_sql=(
                "ALTER TABLE app_commercialtonnagepricing "
                "DROP COLUMN IF EXISTS fleet_discount_percentage;"
            ),
            state_operations=[
                migrations.AddField(
                    model_name='commercialtonnagepricing',
                    name='fleet_discount_percentage',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='commercialtonnagepricing',
            name='base_premium',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commercialtonnagepricing',
            name='tonnage_description',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Motor3Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quote_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('coverage_type', models.CharField(db_index=True, default='THIRD_PARTY', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('CONVERTED', 'Converted To Policy'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('proposed_cover_start_date', models.CharField(blank=True, max_length=32, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('policy_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('payload', models.JSONField()),
                ('normalized_payload', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motor3_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['user', '-date_created'], name='app_motor3q_user_id_168268_idx'), models.Index(fields=['status', '-date_created'], name='app_motor3q_status_b5a377_idx')],
            },
        ),
    ]
