# Generated by Django 4.2.16 on 2026-01-01 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_commercialtonnagepricing_fleet_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorpolicy',
            name='valuation_marked_at',
            field=models.DateTimeField(blank=True, help_text='When the admin marked the valuation status', null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='valuation_marked_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who marked valuation status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motor_policies_valuations_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='valuation_notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes about valuation (optional)'),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='valuation_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Valuation'), ('VALUED', 'Valuation Approved'), ('REJECTED', 'Valuation Rejected')], db_index=True, default='PENDING', help_text='Manual valuation status set by admin for products requiring valuation', max_length=20, null=True),
        ),
    ]
