# Generated by Django 4.2.16 on 2026-01-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_motorpolicy_valuation_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_certificate_preview_url',
            field=models.URLField(blank=True, help_text='URL to DMVIC Certificate Preview PDF (from IntermediaryIntegration/PreviewTypeACertificate)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PREVIEW_GENERATED', 'Preview Generated'), ('ISSUED', 'Issued'), ('FAILED', 'Failed'), ('NO_INVENTORY', 'No Inventory')], help_text='DMVIC certificate generation status', max_length=20, null=True),
        ),
    ]
