# Generated by Django 4.2.16 on 2026-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_motorpolicy_dmvic_certificate_preview_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuserprofile',
            name='ira_number',
            field=models.CharField(blank=True, help_text='Insurance Regulatory Authority registration number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staffuserprofile',
            name='ira_verified',
            field=models.BooleanField(default=False, help_text='Whether the IRA number has been verified by admin'),
        ),
    ]
