# Generated by Django 4.2.16 on 2026-01-18 20:56

from django.db import migrations, models


def backfill_missing_ira_numbers(apps, schema_editor):
    StaffUserProfile = apps.get_model('app', 'StaffUserProfile')

    try:
        from django.db.models import Q
        missing_q = Q(ira_number__isnull=True) | Q(ira_number='')
        qs = StaffUserProfile.objects.filter(missing_q)
    except Exception:
        qs = StaffUserProfile.objects.filter(ira_number__isnull=True)

    for profile in qs.iterator():
        prefix = (getattr(profile, 'agent_prefix', None) or 'AGT').strip() or 'AGT'
        code = getattr(profile, 'agent_code', None)
        base = f"PENDING-{prefix}{code}"
        candidate = base
        i = 1

        # Ensure uniqueness (unique=True on the column)
        while StaffUserProfile.objects.filter(ira_number=candidate).exclude(pk=profile.pk).exists():
            suffix = f"-{i}"
            candidate = (base[: 50 - len(suffix)] + suffix) if len(base) + len(suffix) > 50 else (base + suffix)
            i += 1

        profile.ira_number = candidate
        profile.ira_verified = False
        profile.save(update_fields=['ira_number', 'ira_verified'])


def noop_reverse(apps, schema_editor):
    # No safe automatic reverse for placeholder IRA numbers.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_staffuserprofile_ira_number_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_missing_ira_numbers, noop_reverse),
        migrations.AlterField(
            model_name='staffuserprofile',
            name='ira_number',
            field=models.CharField(help_text='Insurance Regulatory Authority registration number', max_length=50, unique=True),
        ),
    ]
