# Generated by Django 4.2.16 on 2026-01-25 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_staffuserprofile_ira_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(help_text='6-digit verification code', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(help_text='Expiration timestamp for the code')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the code was successfully verified', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that requested verification', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Code',
                'verbose_name_plural': 'Email Verification Codes',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['user', '-date_created'], name='app_emailve_user_id_b624b8_idx'), models.Index(fields=['code', 'is_verified'], name='app_emailve_code_8bd647_idx')],
            },
        ),
    ]
