# Generated by Django 4.2.7 on 2025-09-19 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250912_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('insurance_type', models.CharField(choices=[('MOTOR_PRIVATE', 'Motor Private'), ('MOTOR_COMMERCIAL', 'Motor Commercial'), ('MOTOR_PSV', 'Motor PSV'), ('MOTOR_MOTORCYCLE', 'Motor Motorcycle'), ('MEDICAL', 'Medical'), ('WIBA', 'WIBA'), ('LAST_EXPENSE', 'Last Expense')], max_length=20)),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CONVERTED', 'Converted to Policy')], default='DRAFT', max_length=20)),
                ('form_data', models.JSONField()),
                ('base_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('training_levy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stamp_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dmvic_data', models.JSONField(blank=True, null=True)),
                ('textract_data', models.JSONField(blank=True, null=True)),
                ('selected_underwriter', models.CharField(blank=True, max_length=100, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.CharField(max_length=50)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('processing_time', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='app.insurancequotation')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotorInsuranceDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_registration', models.CharField(max_length=20)),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_type', models.CharField(choices=[('THIRD_PARTY', 'Third Party'), ('COMPREHENSIVE', 'Comprehensive')], max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_id_number', models.CharField(max_length=15)),
                ('owner_kra_pin', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cover_start_date', models.DateField()),
                ('cover_end_date', models.DateField()),
                ('vehicle_usage', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=30, null=True)),
                ('seating_capacity', models.IntegerField(blank=True, null=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motor_details', to='app.insurancequotation')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('processing_status', models.CharField(default='UPLOADED', max_length=20)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.insurancequotation')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
    ]
