# Generated by Django 4.2.16 on 2025-09-30 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_cover_type_field_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('coverage_name', models.CharField(max_length=100)),
                ('coverage_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pricing_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Sum Insured'), ('FIXED', 'Fixed Amount'), ('RATE', 'Rate per Unit')], max_length=20)),
                ('default_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_optional', models.BooleanField(default=True)),
                ('applicable_to', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['coverage_name'],
            },
        ),
        migrations.CreateModel(
            name='MandatoryLevy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('levy_name', models.CharField(max_length=100, unique=True)),
                ('levy_code', models.CharField(max_length=20, unique=True)),
                ('levy_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20)),
                ('levy_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Mandatory Levies',
                'ordering': ['levy_name'],
            },
        ),
        migrations.CreateModel(
            name='Underwriter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_code', models.CharField(max_length=20, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('supported_categories', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-rating', 'company_name'],
            },
        ),
        migrations.RemoveField(
            model_name='psvpllprice',
            name='underwriter',
        ),
        migrations.AlterModelOptions(
            name='commercialtonnagepricing',
            options={'ordering': ['tonnage_from']},
        ),
        migrations.AlterModelOptions(
            name='motorcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Motor Category', 'verbose_name_plural': 'Motor Categories'},
        ),
        migrations.AlterModelOptions(
            name='motorcovertype',
            options={'ordering': ['category', 'sort_order', 'name'], 'verbose_name': 'Motor Cover Type (Legacy)', 'verbose_name_plural': 'Motor Cover Types (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='motorpricing',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AlterModelOptions(
            name='motorsubcategory',
            options={'ordering': ['category', 'subcategory_name'], 'verbose_name_plural': 'Motor Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='vehicleadjustmentfactor',
            options={'ordering': ['factor_type', 'factor_key']},
        ),
        migrations.RemoveIndex(
            model_name='commercialtonnagepricing',
            name='app_commerc_subcate_e8bd1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='commercialtonnagepricing',
            name='app_commerc_tonnage_f80068_idx',
        ),
        migrations.RemoveIndex(
            model_name='motorpricing',
            name='app_motorpr_effecti_422a7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='motorpricing',
            name='app_motorpr_subcate_de9e23_idx',
        ),
        migrations.RemoveIndex(
            model_name='motorpricing',
            name='app_motorpr_underwr_d2a02b_idx',
        ),
        migrations.RemoveIndex(
            model_name='motorsubcategory',
            name='app_motorsu_subcate_2244fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='motorsubcategory',
            name='app_motorsu_product_962074_idx',
        ),
        migrations.AlterUniqueTogether(
            name='motorpricing',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='motorsubcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='motorcategory',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='motorcovertype',
            name='cover_type',
        ),
        migrations.RemoveField(
            model_name='motorinsurancedetails',
            name='cover_type',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='agent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='document_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='environment',
            field=models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='policy_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='upload_method',
            field=models.CharField(choices=[('Django', 'Django Backend'), ('S3', 'AWS S3')], default='Django', max_length=20),
        ),
        migrations.AddField(
            model_name='motorinsurancedetails',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_details', to='app.motorsubcategory'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialtonnagepricing',
            name='base_premium',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commercialtonnagepricing',
            name='effective_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commercialtonnagepricing',
            name='tonnage_description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialtonnagepricing',
            name='underwriter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tonnage_pricing', to='app.insuranceprovider'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.insurancequotation'),
        ),
        migrations.AlterField(
            model_name='insurancequotation',
            name='insurance_type',
            field=models.CharField(choices=[('MOTOR_PRIVATE', 'Motor Private'), ('MOTOR_COMMERCIAL', 'Motor Commercial'), ('MOTOR_PSV', 'Motor PSV'), ('MOTOR_MOTORCYCLE', 'Motor Motorcycle'), ('MOTOR_TUKTUK', 'Motor TukTuk'), ('MOTOR_SPECIAL', 'Motor Special Classes'), ('MEDICAL', 'Medical'), ('WIBA', 'WIBA'), ('LAST_EXPENSE', 'Last Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorcategory',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='motorcovertype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_cover_types', to='app.motorcategory'),
        ),
        migrations.AlterField(
            model_name='motorpricing',
            name='base_premium',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='motorpricing',
            name='effective_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='motorpricing',
            name='minimum_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='motorpricing',
            name='pricing_factors',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='motorsubcategory',
            name='additional_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='motorsubcategory',
            name='pricing_requirements',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='motorsubcategory',
            name='product_type',
            field=models.CharField(choices=[('TOR', 'Time on Risk'), ('THIRD_PARTY', 'Third Party'), ('THIRD_PARTY_EXT', 'Third Party with Extensions'), ('COMPREHENSIVE', 'Comprehensive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorsubcategory',
            name='subcategory_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='motorsubcategory',
            name='subcategory_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='commercialtonnagepricing',
            unique_together={('subcategory', 'underwriter', 'tonnage_from', 'tonnage_to', 'effective_from')},
        ),
        migrations.AlterUniqueTogether(
            name='motorpricing',
            unique_together={('subcategory', 'underwriter', 'effective_from')},
        ),
        migrations.DeleteModel(
            name='PSVPLLPrice',
        ),
        migrations.RemoveField(
            model_name='commercialtonnagepricing',
            name='fleet_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='base_rate_max',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='base_rate_min',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='excess_protector_minimum',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='excess_protector_rate',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='insurance_training_levy_rate',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='loss_of_use_amount',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='loss_of_use_coverage',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='pcf_levy_rate',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='pvt_minimum',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='pvt_rate',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='radio_limit',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='radio_percentage',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='stamp_duty',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='sum_insured_max',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='sum_insured_min',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='windscreen_limit',
        ),
        migrations.RemoveField(
            model_name='motorpricing',
            name='windscreen_percentage',
        ),
        migrations.RemoveField(
            model_name='motorsubcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='motorsubcategory',
            name='extendible_variant',
        ),
        migrations.RemoveField(
            model_name='motorsubcategory',
            name='field_validations',
        ),
        migrations.RemoveField(
            model_name='motorsubcategory',
            name='is_extendible',
        ),
    ]
