# Generated by Django 4.2.16 on 2025-10-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_claim_claimdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorpolicy',
            name='extension_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='last_extension_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='original_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='app.motorpolicy'),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='renewal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='total_extensions_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
