# Generated by Django 4.2.16 on 2025-10-05 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_add_renewal_extension_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Product Line',
                'verbose_name_plural': 'Product Lines',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('pricing_model', models.CharField(choices=[('FLAT', 'Flat Rate'), ('TIERED', 'Tiered / Bracket'), ('AGE_BASED', 'Age Based'), ('FAMILY', 'Family Bundle'), ('CUSTOM', 'Custom Adapter')], default='FLAT', max_length=20)),
                ('form_schema', models.JSONField(default=dict, help_text='Dynamic form definition used by frontend renderer')),
                ('base_rates', models.JSONField(blank=True, default=dict, help_text='Base pricing data (varies by pricing_model)')),
                ('additional_rules', models.JSONField(blank=True, default=dict, help_text='Eligibility & validation rules')),
                ('requires_manual_underwriting', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.productline')),
            ],
            options={
                'verbose_name': 'Product Configuration',
                'verbose_name_plural': 'Product Configurations',
                'ordering': ['line', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GenericQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quote_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('form_data', models.JSONField(default=dict, help_text='Raw client-provided form inputs')),
                ('pricing_input', models.JSONField(blank=True, default=dict, help_text='Normalized data passed into adapter')),
                ('pricing_breakdown', models.JSONField(blank=True, default=dict, help_text='Result from pricing adapter incl. levies')),
                ('selected_underwriter', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_UNDERWRITER', 'Needs Underwriter'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to Policy')], db_index=True, default='DRAFT', max_length=20)),
                ('requires_manual_underwriting', models.BooleanField(default=False, help_text='Copied from product at creation')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generic_quotes', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='app.productline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='app.productconfiguration')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='GenericPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policy_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('client_details', models.JSONField(help_text='Client info (PII)')),
                ('coverage_details', models.JSONField(default=dict, help_text='Coverage specifics / sums / plan tiers')),
                ('underwriter_details', models.JSONField(blank=True, null=True)),
                ('premium_breakdown', models.JSONField(help_text='Pricing breakdown (base, levies, total)')),
                ('payment_details', models.JSONField(default=dict)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_PAYMENT', max_length=20)),
                ('cover_start_date', models.DateField(blank=True, null=True)),
                ('cover_end_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.IntegerField(default=0)),
                ('is_renewal', models.BooleanField(default=False)),
                ('renewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='app.productline')),
                ('original_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='app.genericpolicy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='app.productconfiguration')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='app.genericquote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generic_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='genericquote',
            index=models.Index(fields=['quote_number'], name='app_generic_quote_n_2883f7_idx'),
        ),
        migrations.AddIndex(
            model_name='genericquote',
            index=models.Index(fields=['status', '-date_created'], name='app_generic_status_4e5699_idx'),
        ),
        migrations.AddIndex(
            model_name='genericquote',
            index=models.Index(fields=['agent', '-date_created'], name='app_generic_agent_i_c69c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='genericpolicy',
            index=models.Index(fields=['policy_number'], name='app_generic_policy__f68167_idx'),
        ),
        migrations.AddIndex(
            model_name='genericpolicy',
            index=models.Index(fields=['status', '-date_created'], name='app_generic_status_676e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='genericpolicy',
            index=models.Index(fields=['user', '-date_created'], name='app_generic_user_id_95d458_idx'),
        ),
    ]
