# Generated by Django 4.2.16 on 2025-10-10 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_manualquote'),
    ]

    operations = [
        # The legacy tables may have been dropped earlier. Use state-only changes
        # to keep the migration graph consistent without requiring the tables to exist.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='genericquote',
                    name='agent',
                ),
                migrations.RemoveField(
                    model_name='genericquote',
                    name='line',
                ),
                migrations.RemoveField(
                    model_name='genericquote',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='productconfiguration',
                    name='line',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='manualquote',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='manualquote',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='manualquote',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='insurancequotation',
            name='insurance_type',
            field=models.CharField(choices=[('MOTOR_PRIVATE', 'Motor Private'), ('MOTOR_COMMERCIAL', 'Motor Commercial'), ('MOTOR_PSV', 'Motor PSV'), ('MOTOR_MOTORCYCLE', 'Motor Motorcycle'), ('MOTOR_TUKTUK', 'Motor TukTuk'), ('MOTOR_SPECIAL', 'Motor Special Classes'), ('MEDICAL', 'Medical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manualquote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='GenericPolicy',
        ),
        migrations.DeleteModel(
            name='GenericQuote',
        ),
        migrations.DeleteModel(
            name='ProductConfiguration',
        ),
        migrations.DeleteModel(
            name='ProductLine',
        ),
    ]
