# Generated by Django 4.2.16 on 2025-10-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_genericquote_agent_remove_genericquote_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualquote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='manualquote',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='manualquote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
