# Generated by Django 4.2.16 on 2025-10-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_commissionrule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commissionrule',
            new_name='app_commiss_priorit_0bd42b_idx',
            old_name='app_commrule_prio_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionrule',
            new_name='app_commiss_is_acti_d262b5_idx',
            old_name='app_commrule_active_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionrule',
            new_name='app_commiss_line_ke_29d703_idx',
            old_name='app_commrule_linekey_idx',
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='display_mode',
            field=models.CharField(choices=[('NET', 'NET - Base Premium Only'), ('GROSS', 'GROSS - Premium with Levies')], default='GROSS', help_text='Display NET (base premium) or GROSS (with levies) in underwriter comparison', max_length=10),
        ),
    ]
