# Generated by Django 4.2.16 on 2025-10-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_drop_motorcovertype_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_banners/'),
        ),
    ]
