# Generated by Django 4.2.16 on 2025-10-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_extendible_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyextension',
            name='underwriter',
        ),
        migrations.DeleteModel(
            name='ExtensionReminder',
        ),
        migrations.DeleteModel(
            name='PolicyExtension',
        ),
    ]
