# Generated by Django 4.2.16 on 2025-11-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_documentupload_motor_policy_dmvicvehiclesearch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_api_request_number',
            field=models.CharField(blank=True, help_text='DMVIC API Request Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_certificate_number',
            field=models.CharField(blank=True, db_index=True, help_text='DMVIC Certificate Number (e.g., A1020701)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_certificate_pdf_url',
            field=models.URLField(blank=True, help_text='URL to DMVIC Certificate PDF', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_certificate_type',
            field=models.CharField(blank=True, choices=[('A', 'Type A - PSV'), ('B', 'Type B - Comprehensive'), ('C', 'Type C - Third Party'), ('D', 'Type D - Special')], help_text='DMVIC Certificate Type', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when DMVIC issuance was confirmed (post-logbook verification)', null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_issuance_request_id',
            field=models.CharField(blank=True, help_text='DMVIC Issuance Request ID (e.g., AF-AA0012)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_issued_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when DMVIC certificate was issued', null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_ref_no',
            field=models.CharField(blank=True, help_text='DMVIC Reference Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='dmvic_transaction_no',
            field=models.CharField(blank=True, help_text='DMVIC Transaction Number', max_length=50, null=True),
        ),
    ]
