"""
Django settings for insurance project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from dotenv import load_dotenv

from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

load_dotenv(dotenv_path=BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'o7c#_r_4vjk!1l!#h8r7bi*v*&u=%0z$r()3hkft!$-jayiq21')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    'storages',
    'django_ses',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'insurance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'insurance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# Database configuration
# Elastic Beanstalk automatically sets RDS_* environment variables when you attach an RDS database
if 'RDS_HOSTNAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
            'OPTIONS': {
                'connect_timeout': 60,
            },
        }
    }
else:
    # Development/fallback configuration using DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            env='DATABASE_URL',
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
        )
    }

# Use faster in-memory DB for tests if not explicitly overridden
if os.environ.get('USE_IN_MEMORY_TEST_DB', '1') == '1':
    DATABASES['default']['TEST'] = {
        'NAME': ':memory:'
    }

# If running tests and a non-sqlite engine is configured (e.g., Postgres without createdb perms),
# force an in-memory sqlite database to avoid permission issues.
if 'test' in sys.argv:
    engine = DATABASES['default'].get('ENGINE', '')
    if 'sqlite' not in engine:
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
            'TEST': { 'NAME': ':memory:' }
        }
    # Bypass legacy conflicting migrations for speed & to avoid renamed field index errors
    MIGRATION_MODULES = {
        'app': None,
    }


# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_REDIRECT_EXEMPT = [
        r'^health/$',  # AWS health check
        r'^status/$',  # Application health check
    ]
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_PRELOAD = True


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Change default Auth model
AUTH_USER_MODEL = "app.User"

# Media (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Optional: Use AWS S3 for media in production when env vars are set
USE_S3_MEDIA = os.getenv('USE_S3_MEDIA', '0') in ('1', 'true', 'True')
# Support both new and legacy env names
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME') or os.getenv('S3_BUCKET')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME') or os.getenv('AWS_REGION')
_bucket = AWS_STORAGE_BUCKET_NAME
_region = AWS_S3_REGION_NAME
AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN') or (
    (f"{_bucket}.s3.{_region}.amazonaws.com" if _bucket and _region else (f"{_bucket}.s3.amazonaws.com" if _bucket else None))
)

if USE_S3_MEDIA and AWS_STORAGE_BUCKET_NAME:
    # Django 4+ prefers STORAGES settings
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    # Use unsigned URLs - bucket policy grants public read access to campaign_banners/*
    # URLs never expire and work directly without query string parameters
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    # Do NOT set AWS_DEFAULT_ACL - bucket has ACLs disabled, using bucket policy instead
    # Build media URL from custom domain if provided
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

# Django REST Framework configuration - JSON only (disable browsable API)
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 2000,
    "EXCEPTION_HANDLER": "app.utils.custom_exception_handler",
}

SIMPLE_JWT = {
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "ROTATE_REFRESH_TOKENS": True,
}

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'https://app.patabima.co.ke').split(',')
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "AUTH",
    "JWTAUTH",
    "CPARAMS",
    "AUTHORIZATION",
    "HTTP_AUTHORIZATION",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Services backend base URL for proxying new motor endpoints
SERVICES_BACKEND_BASE_URL = os.getenv('SERVICES_BACKEND_BASE_URL', 'http://127.0.0.1:8001')

# ===== EMAIL CONFIGURATION (AWS SES) =====
# Email backend configuration
# Use 'django_ses.SESBackend' for production with AWS SES
# Use 'django.core.mail.backends.console.EmailBackend' for development/testing
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# AWS SES Configuration
AWS_SES_REGION_NAME = os.getenv('AWS_SES_REGION_NAME', 'us-east-1')
AWS_SES_REGION_ENDPOINT = os.getenv('AWS_SES_REGION_ENDPOINT', f'email.{AWS_SES_REGION_NAME}.amazonaws.com')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@patabima.co.ke')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# AWS SES Auto-throttling (0.5 = send at half max rate)
AWS_SES_AUTO_THROTTLE = float(os.getenv('AWS_SES_AUTO_THROTTLE', '0.5'))

# Email configuration for notifications
EMAIL_SUBJECT_PREFIX = os.getenv('EMAIL_SUBJECT_PREFIX', '[PataBima] ')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'admin@patabima.co.ke')

# AWS Credentials (shared with S3 if already configured)
# If not set, boto3 will use AWS CLI credentials or EC2 instance role
if not os.getenv('AWS_ACCESS_KEY_ID'):
    # Try to use AWS CLI credentials
    pass  # boto3 will automatically use ~/.aws/credentials or EC2 instance role


# ===== DMVIC INTEGRATION CONFIGURATION =====
# DMVIC (Department of Motor Vehicle Insurance Coordinator) API Integration
# Used for vehicle verification, certificate issuance, and validation

# DMVIC API Base URL
DMVIC_BASE_URL = os.getenv('DMVIC_BASE_URL', 'https://uat-api.dmvic.com')

# DMVIC Authentication Credentials
DMVIC_USERNAME = os.getenv('DMVIC_USERNAME', None)
DMVIC_PASSWORD = os.getenv('DMVIC_PASSWORD', None)
DMVIC_CLIENT_ID = os.getenv('DMVIC_CLIENT_ID', None)

# DMVIC Member Company Code (assigned by DMVIC)
DMVIC_MEMBER_CODE = os.getenv('DMVIC_MEMBER_CODE', 'PATABIMA')

# DMVIC Certificate Authentication (.pfx file)
# Path relative to BASE_DIR or absolute path
DMVIC_PFX_PATH = os.getenv('DMVIC_PFX_PATH', 'dmvic_credentials/PatabimaAgencyUAT.pfx')
DMVIC_PASSPHRASE = os.getenv('DMVIC_PASSPHRASE', None)

# DMVIC Integration Enabled Flag
# Set to False to disable DMVIC integration (falls back to mock data)
DMVIC_ENABLED = os.getenv('DMVIC_ENABLED', 'False').lower() == 'true'


# ===== MOTOR2 STATIC DATA VERSIONING =====
# Motor2 Static Data Version (for hybrid static + background sync)
# Increment this version when categories or subcategories change
# Format: MAJOR.MINOR.PATCH (Semantic Versioning)
# - MAJOR: Breaking changes (schema changes)
# - MINOR: New categories/subcategories added
# - PATCH: Bug fixes, description updates
MOTOR2_STATIC_VERSION = os.getenv('MOTOR2_STATIC_VERSION', '1.0.0')


# ===== LOGGING CONFIGURATION =====
# Logging configuration for CloudWatch (production) and console (development)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if not DEBUG else 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'app': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'dmvic': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Add file logging only in production (Linux environment)
if not DEBUG and os.path.exists('/var/log'):
    LOGGING['handlers']['file'] = {
        'class': 'logging.FileHandler',
        'filename': '/var/log/django.log',
        'formatter': 'verbose',
    }
    # Add file handler to all loggers in production
    for logger in LOGGING['loggers'].values():
        logger['handlers'].append('file')
